-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local err_pb = require("PixelFarm/PBLua/err_pb")
module('item_pb')


local ITEMREQUEST = protobuf.Descriptor();
local ITEMRESPONSE = protobuf.Descriptor();
local ITEMRESPONSE_CODE_FIELD = protobuf.FieldDescriptor();
local ITEMRESPONSE_ERR_FIELD = protobuf.FieldDescriptor();
local ITEMRESPONSE_ITEMS_FIELD = protobuf.FieldDescriptor();
local ITEM = protobuf.Descriptor();
local ITEM_ID_FIELD = protobuf.FieldDescriptor();
local ITEM_NAME_FIELD = protobuf.FieldDescriptor();
local ITEM_PRICE_FIELD = protobuf.FieldDescriptor();
local ITEM_EFFECT_FIELD = protobuf.FieldDescriptor();
local ITEM_DESC_FIELD = protobuf.FieldDescriptor();
local ITEM_MIXS_FIELD = protobuf.FieldDescriptor();
local ITEM_ITEMID_FIELD = protobuf.FieldDescriptor();
local ITEM_HEROID_FIELD = protobuf.FieldDescriptor();
local MIX = protobuf.Descriptor();
local MIX_ITEMID_FIELD = protobuf.FieldDescriptor();
local MIX_NUM_FIELD = protobuf.FieldDescriptor();

ITEMREQUEST.name = "ItemRequest"
ITEMREQUEST.full_name = ".msg.ItemRequest"
ITEMREQUEST.nested_types = {}
ITEMREQUEST.enum_types = {}
ITEMREQUEST.fields = {}
ITEMREQUEST.is_extendable = false
ITEMREQUEST.extensions = {}
ITEMRESPONSE_CODE_FIELD.name = "code"
ITEMRESPONSE_CODE_FIELD.full_name = ".msg.ItemResponse.code"
ITEMRESPONSE_CODE_FIELD.number = 1
ITEMRESPONSE_CODE_FIELD.index = 0
ITEMRESPONSE_CODE_FIELD.label = 1
ITEMRESPONSE_CODE_FIELD.has_default_value = false
ITEMRESPONSE_CODE_FIELD.default_value = nil
ITEMRESPONSE_CODE_FIELD.enum_type = ERR_PB_RESPONSECODE
ITEMRESPONSE_CODE_FIELD.type = 14
ITEMRESPONSE_CODE_FIELD.cpp_type = 8

ITEMRESPONSE_ERR_FIELD.name = "err"
ITEMRESPONSE_ERR_FIELD.full_name = ".msg.ItemResponse.err"
ITEMRESPONSE_ERR_FIELD.number = 2
ITEMRESPONSE_ERR_FIELD.index = 1
ITEMRESPONSE_ERR_FIELD.label = 1
ITEMRESPONSE_ERR_FIELD.has_default_value = false
ITEMRESPONSE_ERR_FIELD.default_value = nil
ITEMRESPONSE_ERR_FIELD.message_type = ERR_PB_ERROR
ITEMRESPONSE_ERR_FIELD.type = 11
ITEMRESPONSE_ERR_FIELD.cpp_type = 10

ITEMRESPONSE_ITEMS_FIELD.name = "items"
ITEMRESPONSE_ITEMS_FIELD.full_name = ".msg.ItemResponse.items"
ITEMRESPONSE_ITEMS_FIELD.number = 3
ITEMRESPONSE_ITEMS_FIELD.index = 2
ITEMRESPONSE_ITEMS_FIELD.label = 3
ITEMRESPONSE_ITEMS_FIELD.has_default_value = false
ITEMRESPONSE_ITEMS_FIELD.default_value = {}
ITEMRESPONSE_ITEMS_FIELD.message_type = _ITEM
ITEMRESPONSE_ITEMS_FIELD.type = 11
ITEMRESPONSE_ITEMS_FIELD.cpp_type = 10

ITEMRESPONSE.name = "ItemResponse"
ITEMRESPONSE.full_name = ".msg.ItemResponse"
ITEMRESPONSE.nested_types = {}
ITEMRESPONSE.enum_types = {}
ITEMRESPONSE.fields = {ITEMRESPONSE_CODE_FIELD, ITEMRESPONSE_ERR_FIELD, ITEMRESPONSE_ITEMS_FIELD}
ITEMRESPONSE.is_extendable = false
ITEMRESPONSE.extensions = {}
ITEM_ID_FIELD.name = "Id"
ITEM_ID_FIELD.full_name = ".msg.Item.Id"
ITEM_ID_FIELD.number = 1
ITEM_ID_FIELD.index = 0
ITEM_ID_FIELD.label = 1
ITEM_ID_FIELD.has_default_value = false
ITEM_ID_FIELD.default_value = 0
ITEM_ID_FIELD.type = 5
ITEM_ID_FIELD.cpp_type = 1

ITEM_NAME_FIELD.name = "Name"
ITEM_NAME_FIELD.full_name = ".msg.Item.Name"
ITEM_NAME_FIELD.number = 2
ITEM_NAME_FIELD.index = 1
ITEM_NAME_FIELD.label = 1
ITEM_NAME_FIELD.has_default_value = false
ITEM_NAME_FIELD.default_value = ""
ITEM_NAME_FIELD.type = 9
ITEM_NAME_FIELD.cpp_type = 9

ITEM_PRICE_FIELD.name = "Price"
ITEM_PRICE_FIELD.full_name = ".msg.Item.Price"
ITEM_PRICE_FIELD.number = 3
ITEM_PRICE_FIELD.index = 2
ITEM_PRICE_FIELD.label = 1
ITEM_PRICE_FIELD.has_default_value = false
ITEM_PRICE_FIELD.default_value = 0
ITEM_PRICE_FIELD.type = 5
ITEM_PRICE_FIELD.cpp_type = 1

ITEM_EFFECT_FIELD.name = "Effect"
ITEM_EFFECT_FIELD.full_name = ".msg.Item.Effect"
ITEM_EFFECT_FIELD.number = 4
ITEM_EFFECT_FIELD.index = 3
ITEM_EFFECT_FIELD.label = 1
ITEM_EFFECT_FIELD.has_default_value = false
ITEM_EFFECT_FIELD.default_value = ""
ITEM_EFFECT_FIELD.type = 9
ITEM_EFFECT_FIELD.cpp_type = 9

ITEM_DESC_FIELD.name = "Desc"
ITEM_DESC_FIELD.full_name = ".msg.Item.Desc"
ITEM_DESC_FIELD.number = 5
ITEM_DESC_FIELD.index = 4
ITEM_DESC_FIELD.label = 1
ITEM_DESC_FIELD.has_default_value = false
ITEM_DESC_FIELD.default_value = ""
ITEM_DESC_FIELD.type = 9
ITEM_DESC_FIELD.cpp_type = 9

ITEM_MIXS_FIELD.name = "Mixs"
ITEM_MIXS_FIELD.full_name = ".msg.Item.Mixs"
ITEM_MIXS_FIELD.number = 6
ITEM_MIXS_FIELD.index = 5
ITEM_MIXS_FIELD.label = 3
ITEM_MIXS_FIELD.has_default_value = false
ITEM_MIXS_FIELD.default_value = {}
ITEM_MIXS_FIELD.message_type = _MIX
ITEM_MIXS_FIELD.type = 11
ITEM_MIXS_FIELD.cpp_type = 10

ITEM_ITEMID_FIELD.name = "ItemId"
ITEM_ITEMID_FIELD.full_name = ".msg.Item.ItemId"
ITEM_ITEMID_FIELD.number = 7
ITEM_ITEMID_FIELD.index = 6
ITEM_ITEMID_FIELD.label = 1
ITEM_ITEMID_FIELD.has_default_value = false
ITEM_ITEMID_FIELD.default_value = ""
ITEM_ITEMID_FIELD.type = 9
ITEM_ITEMID_FIELD.cpp_type = 9

ITEM_HEROID_FIELD.name = "HeroId"
ITEM_HEROID_FIELD.full_name = ".msg.Item.HeroId"
ITEM_HEROID_FIELD.number = 8
ITEM_HEROID_FIELD.index = 7
ITEM_HEROID_FIELD.label = 1
ITEM_HEROID_FIELD.has_default_value = false
ITEM_HEROID_FIELD.default_value = ""
ITEM_HEROID_FIELD.type = 9
ITEM_HEROID_FIELD.cpp_type = 9

ITEM.name = "Item"
ITEM.full_name = ".msg.Item"
ITEM.nested_types = {}
ITEM.enum_types = {}
ITEM.fields = {ITEM_ID_FIELD, ITEM_NAME_FIELD, ITEM_PRICE_FIELD, ITEM_EFFECT_FIELD, ITEM_DESC_FIELD, ITEM_MIXS_FIELD, ITEM_ITEMID_FIELD, ITEM_HEROID_FIELD}
ITEM.is_extendable = false
ITEM.extensions = {}
MIX_ITEMID_FIELD.name = "ItemId"
MIX_ITEMID_FIELD.full_name = ".msg.Mix.ItemId"
MIX_ITEMID_FIELD.number = 1
MIX_ITEMID_FIELD.index = 0
MIX_ITEMID_FIELD.label = 1
MIX_ITEMID_FIELD.has_default_value = false
MIX_ITEMID_FIELD.default_value = 0
MIX_ITEMID_FIELD.type = 5
MIX_ITEMID_FIELD.cpp_type = 1

MIX_NUM_FIELD.name = "Num"
MIX_NUM_FIELD.full_name = ".msg.Mix.Num"
MIX_NUM_FIELD.number = 2
MIX_NUM_FIELD.index = 1
MIX_NUM_FIELD.label = 1
MIX_NUM_FIELD.has_default_value = false
MIX_NUM_FIELD.default_value = 0
MIX_NUM_FIELD.type = 5
MIX_NUM_FIELD.cpp_type = 1

MIX.name = "Mix"
MIX.full_name = ".msg.Mix"
MIX.nested_types = {}
MIX.enum_types = {}
MIX.fields = {MIX_ITEMID_FIELD, MIX_NUM_FIELD}
MIX.is_extendable = false
MIX.extensions = {}

Item = protobuf.Message(ITEM)
ItemRequest = protobuf.Message(ITEMREQUEST)
ItemResponse = protobuf.Message(ITEMRESPONSE)
Mix = protobuf.Message(MIX)

